config/routes.rb
Mx::Application.routes.draw do
  resources :categories
  resources :rooms
  resources :films

  devise_for :users

  post '/test/1' => 'page#test'

  post '/room/add'               => 'rooms#add'
  get  '/room/join/:key'         => 'rooms#join'
  get  '/room/user_event/:key'   => 'rooms#user_event'
  get  '/room/admin_event/:key'  => 'rooms#admin_event'
  post '/room/send_message'      => 'rooms#send_message'
  post '/room/system_message'    => 'rooms#system_message'

  root 'page#index'

end

app/models/category.rb
class Category
  include MongoMapper::Document

  key :name, String
  key :about, String

end

app/models/chat.rb
class Chat
  include MongoMapper::Document

  key :message, String
  timestamps!

end

app/models/film.rb
class Film
  include MongoMapper::Document

  key :name, String
  key :file, String

  one :room

end

app/models/room.rb
class Room
  include MongoMapper::Document

  key :key,       String
  key :users_ids, Array

  belongs_to :film
  many :users, :in => :users_ids
  belongs_to :user
  

end

app/models/user.rb
class User
  include MongoMapper::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  key :email,              String
  key :encrypted_password, String
  key :current_sign_in_ip, String
  key :last_sign_in_ip,    String
  key :sign_in_count,      Integer
  key :current_sign_in_at, Time
  key :last_sign_in_at,    Time
  key :remember_created_at,Time

  attr_accessible :email, :password, :password_confirmation, :encrypted_password, :last_sign_in_at, :current_sign_in_at, :current_sign_in_ip, :last_sign_in_ip, :sign_in_count, :remember_created_at

  many :rooms

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :about)
    end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render action: 'show', status: :created, location: @film }
      else
        format.html { render action: 'new' }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.set(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:name, :file)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def test
    render :json => params
    #session[:session_id]
  end



  def index
    @categories = Category.all
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render action: 'show', status: :created, location: @room }
      else
        format.html { render action: 'new' }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def add
    key  = ("a".."z").to_a.shuffle.join[1..8]
    room = Room.new(:key => key)
    film = Film.find(params[:id])
    room.user = current_user
    film.room = room
    film.save
    
    #
    render :json => film.room
  end

  def join
    room = Room.find_one(:key => params[:key])
    @film = room.film
    room.users << current_user
    room.save
  end

  def admin_event
    room = Room.find_one(:key => params[:key])
    chat = Chat.last
    render :json => [room.users, room.user, chat]
  end

  def user_event
    chat = Chat.last
    room = Room.find_one(:key => params[:key])
    render :json => [room.user, room.users, chat]
  end

  def send_message
    chat = Chat.new(params)
    chat.save
    render :json => chat
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
  end

  private
    def message(type, message)

    end
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:key, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :about
    = f.text_field :about
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table
  %tr
    %th Name
    %th About
    %th
    %th
    %th

  - @categories.each do |category|
    %tr
      %td= category.name
      %td= category.about
      %td= link_to 'Show', category
      %td= link_to 'Edit', edit_category_path(category)
      %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name
%p
  %b About:
  = @category.about

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path

app/views/films/_form.html.haml
= form_for @film do |f|
  - if @film.errors.any?
    #error_explanation
      %h2= "#{pluralize(@film.errors.count, "error")} prohibited this film from being saved:"
      %ul
        - @film.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :file
    = f.text_field :file
  .actions
    = f.submit 'Save'

app/views/films/edit.html.haml
%h1 Editing film

= render 'form'

= link_to 'Show', @film
\|
= link_to 'Back', films_path

app/views/films/index.html.haml
%h1 Listing films

%table
  %tr
    %th Name
    %th File
    %th
    %th
    %th

  - @films.each do |film|
    %tr
      %td= film.name
      %td= film.file
      %td= link_to 'Show', film
      %td= link_to 'Edit', edit_film_path(film)
      %td= link_to 'Destroy', film, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Film', new_film_path

app/views/films/new.html.haml
%h1 New film

= render 'form'

= link_to 'Back', films_path

app/views/films/show.html.haml
.row
  .span9
    %p#notice= notice
    = videojs_rails id: "room_video", sources: { mp4: "/films/mp4/#{@film[:file]}.mp4", webm: "/films/webm/#{@film[:file]}.webm"}, width: "100%", height: "500px"  

  .span3
    %ul#online_users.nav.nav-pills.nav-stacked

.row
  .span9
    %div#online_chat

    %form#text-form
      %input{:type=>'text', :name => 'message', :disabled => "disabled"}
      %button.btn.send_message{:type=> 'submit', :disabled => "disabled"}
        Send
  .span3
    #room_link
      %input{:type => 'text'}
    %a#create_room{:class=> "btn btn-primary", :href=>"##{@film[:_id]}"}
      =t :create_room
    %hr
    %a#start_view{:class=> "btn btn-success", :href=>"##{@film[:_id]}", :disabled => ""}
      =t :start_view

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Mx"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") 
            %img{:src => "/logo.png"}
          .container.nav-collapse
            %ul.nav.pull-right
              -if user_signed_in?
                %li.dropdown
                  %a.dropdown-toggle{"data-toggle"=> "dropdown", :href=>"#"}= current_user.email
                  %ul.dropdown-menu
                    %li= link_to :sign_out, destroy_user_session_path, :method => :delete
              -else
                %li
                  =link_to :sign_in, new_user_session_path



    .container
      .row
        .span12
          %br
          %br
          %br
          %br
          %br
          %br
          %br
          = bootstrap_flash


      = yield
    
      %footer
        %hr
        %p &copy; Company 2013

app/views/page/index.html.haml
%h1 index
%ul
  -@categories.each do |category|
    %li
      %a{:href => "/category/#{category[:_id]}"}
        =category[:name]

//%button{:onclick => "TogetherJS(this); TogetherJSConfig_dontShowClicks = true; return false;"}  
//YaY

app/views/rooms/_form.html.haml
= form_for @room do |f|
  - if @room.errors.any?
    #error_explanation
      %h2= "#{pluralize(@room.errors.count, "error")} prohibited this room from being saved:"
      %ul
        - @room.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :key
    = f.text_field :key
  .field
    = f.label :admin
    = f.text_field :admin
  .actions
    = f.submit 'Save'

app/views/rooms/edit.html.haml
%h1 Editing room

= render 'form'

= link_to 'Show', @room
\|
= link_to 'Back', rooms_path

app/views/rooms/index.html.haml
%h1 Listing rooms

%table
  %tr
    %th Key
    %th Admin
    %th
    %th
    %th

  - @rooms.each do |room|
    %tr
      %td= room.key
      %td= room.admin
      %td= link_to 'Show', room
      %td= link_to 'Edit', edit_room_path(room)
      %td= link_to 'Destroy', room, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Room', new_room_path

app/views/rooms/join.html.haml
.row
  .span9
    %p#notice= notice
    = videojs_rails id: "room_video", sources: { mp4: "/films/mp4/#{@film[:file]}.mp4", webm: "/films/webm/#{@film[:file]}.webm"}, width: "100%", height: "500px"  

  .span3
    %ul#online_users.nav.nav-pills.nav-stacked

.row
  .span9
    %div#online_chat

    %form#text-form
      %input{:type=>'text', :name => 'message', :disabled => "disabled"}
      %button.btn.send_message{:type=> 'submit', :disabled => "disabled"}
        Send
  .span3
    #room_link
      %input{:type => 'text'}
    %a#connect_room{:class=> "btn btn-primary", :href=>"##{@film[:_id]}"}
      =t :join_room

app/views/rooms/new.html.haml
%h1 New room

= render 'form'

= link_to 'Back', rooms_path

app/views/rooms/show.html.haml
%p#notice= notice

%p
  %b Key:
  = @room.key
%p
  %b Admin:
  = @room.admin

= link_to 'Edit', edit_room_path(@room)
\|
= link_to 'Back', rooms_path